version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env

  salesbot-component:
    image: salesbot-component 
    build:
      context: ../salesbot-component
      dockerfile:  Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ../salesbot-component:/app
    env_file:
      - ../.env

  lucidify:
    image: lucidify
    build:
      context: ../
      dockerfile:  lucidify/Dockerfile.dev
    ports:
      - '3001:3000'
    volumes:
      - ../lucidify:/app
      - ../lucidify-chat:/lucidify-chat
    env_file:
      - ../.env

  go-api:
    image: backend/go-api 
    build:
      context: ../backend/go-api
      dockerfile:  Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ../backend/go-api:/app
    env_file:
      - ../.env

  openai-cookbook-q-and-a:
    build:
      context: ../backend/openai-cookbook-q-and-a
      dockerfile: Dockerfile.dev
    volumes:
      - ../backend/openai-cookbook-q-and-a:/app
    ports:
      - "8081:8080"
    env_file:
      - ../.env

volumes:
  db:
    driver: local
