version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ../.env

  # frontend:
  #   image: sheffessions_fe 
  #   build:
  #     context: ../frontend/sheffessions
  #     dockerfile:  Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ../frontend/sheffessions:/app
  #   env_file:
  #     - ../.env

  backend:
    image: go-openai 
    build:
      context: ../backend
      dockerfile:  Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ../backend:/app
    env_file:
      - ../.env

volumes:
  db:
    driver: local
